server:
  port: 9697

spring:
  application:
    name: adventure
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-214-3-162.compute-1.amazonaws.com:5432/d8rbp405eu84sd
    username: zyqesvliihkkah
    password: c2fcf61b39689075ee656688ac4e5e2c911029df59abf6b407307e5020a2f9bc

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
