CREATE TABLE OPTIONS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRIPTION VARCHAR(100) NOT NULL,
	OPT_1_TEXT VARCHAR(20) NOT NULL,
	OPT_2_TEXT VARCHAR(20) NOT NULL,
	OPT_3_TEXT VARCHAR(20) NOT NULL,
	OPT_1_VALUE INT NOT NULL,
	OPT_2_VALUE INT NOT NULL,
	OPT_3_VALUE INT NOT NULL
);

CREATE TABLE SCORES(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    S_HOUR VARCHAR(10) NOT NULL,
    S_MINUTE VARCHAR(10) NOT NULL,
    S_SECOND VARCHAR(10) NOT NULL,
    S_TIMESTAMP DATE
);